global:
  runner: 
    containers:
    - image: razorci/golang:1.14
    - image: bitnami/mongodb:4.4.1
      environment:
      # - MONGODB_ROOT_PASSWORD=${DB_ROOT_PASS}
      # - MONGODB_DATABASE=${DB_NAME}
      # - MONGODB_USERNAME=${DB_USER}
      # - MONGODB_PASSWORD=${DB_PASS}

      - MONGODB_ROOT_PASSWORD=adminpass
      - MONGODB_DATABASE=test
      - MONGODB_USERNAME=appuser
      - MONGODB_PASSWORD=apppass
tasks:
  test:
    steps:
    - checkout
    - commands:
      - |
        cd server
        export DB_CONNECTION=mongodb://appuser:apppass@localhost:27017/test
        export DB_NAME=test
        echo $DB_CONNECTION
        echo $DB_NAME
        go mod download
        go test ./...
  hello-job:
      runner: sonarsource/sonar-scanner-cli
      steps:
   
      - checkout    
      - commands:
        - |
          sonar-scanner \
           -Dsonar.projectKey=golang \
           -Dsonar.sources=. \
           -Dsonar.host.url=http://13.235.82.212:9000 \
           -Dsonar.login=7e1d73452a9087e3e352fe5bbcb734c7e8e4f550
